defaults:
  - training: defaults
  - model: defaults
  - dataset: alto_word

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: supervised

dataset:
  alto_word_humanistique:
    supervised: True

model:
  background:
    init:
      constant: [0.3662476,0.22495858,0.18312915]

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 100
